language: python
sudo: false
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
matrix:
  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


install: 
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install tqdm==2.2.3
  - pip3 install gym==0.7.4
  - pip3 install boardgame2 
  - pip3 install pytest


script: 
  - cd ./Project/
  - pytest reversi.py